---
name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format
        run: find src include test -iregex '.*\.\(c\|h\|cpp\|hpp\|cc\|hh\|cxx\|hxx\)$' | xargs clang-format -n -Werror
  build-linux:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: build-linux64-debug
      BUILD_LIBS_DIR: build-linux64-libs-debug
      CMAKE_BUILD_TYPE: Debug
    steps:
      - uses: actions/checkout@v3
      - name: Build without getlibs
        run: |
          echo "CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
          cmake -S . -B $BUILD_DIR
          cmake --build $BUILD_DIR --config $CMAKE_BUILD_TYPE
          (cd $BUILD_DIR && ctest -C $CMAKE_BUILD_TYPE --output-on-failure)
      - name: Get dependencies
        run: |
          CMAKE_BUILD_TYPE=Release ./getlibs.sh linux64
      - name: Build with getlibs
        run: |
          echo "CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
          cmake -S . -B $BUILD_LIBS_DIR -DCMAKE_PREFIX_PATH="$PWD/libs-linux64" -DFIND_FATAL=ON
          cmake --build $BUILD_LIBS_DIR --config $CMAKE_BUILD_TYPE
          (cd $BUILD_LIBS_DIR && ctest -C $CMAKE_BUILD_TYPE --output-on-failure)
  build-win:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: build-win64-debug
      BUILD_LIBS_DIR: build-win64-libs-debug
      CMAKE_BUILD_TYPE: Debug
      CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/toolchains/mingw.cmake
    steps:
      - uses: actions/checkout@v3
      - name: Install cross-compiler
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cmake make g++-mingw-w64-x86-64 mingw-w64-x86-64-dev mingw-w64-tools wine wine-binfmt doctest-dev libboost-all-dev
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          export WINEPATH=$(./mingw-winepath.sh)
      - name: Build without getlibs
        run: |
          echo "CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
          echo "CMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}"
          cmake -S . -B $BUILD_DIR
          cmake --build $BUILD_DIR --config $CMAKE_BUILD_TYPE
          (cd $BUILD_DIR && ctest -C $CMAKE_BUILD_TYPE --output-on-failure)
      - name: Get dependencies
        run: |
          CMAKE_BUILD_TYPE=Release CMAKE_TOOLCHAIN_FILE="$PWD/toolchains/mingw.cmake" ./getlibs.sh win64
      - name: Build with getlibs
        run: |
          echo "CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
          echo "CMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}"
          cmake -S . -B $BUILD_LIBS_DIR -DCMAKE_PREFIX_PATH="$PWD/libs-win64" -DFIND_FATAL=ON
          cmake --build $BUILD_LIBS_DIR --config $CMAKE_BUILD_TYPE
          (cd $BUILD_LIBS_DIR && ctest -C $CMAKE_BUILD_TYPE --output-on-failure)
  build-macos:
    runs-on: macos-latest
    env:
      BUILD_DIR: build-macos64-debug
      BUILD_LIBS_DIR: build-macos64-libs-debug
      CMAKE_BUILD_TYPE: Debug
    steps:
      - uses: actions/checkout@v3
      - name: Build without getlibs
        run: |
          cmake -S . -B $BUILD_DIR
          cmake --build $BUILD_DIR --config $CMAKE_BUILD_TYPE
          (cd $BUILD_DIR && ctest -C $CMAKE_BUILD_TYPE --output-on-failure)
      - name: Get dependencies
        run: |
          CMAKE_BUILD_TYPE=Release ./getlibs.sh macos64
      - name: Build with getlibs
        run: |
          cmake -S . -B $BUILD_LIBS_DIR -DCMAKE_PREFIX_PATH="$PWD/libs-macos64" -DFIND_FATAL=ON
          cmake --build $BUILD_LIBS_DIR --config $CMAKE_BUILD_TYPE
          (cd $BUILD_LIBS_DIR && ctest -C $CMAKE_BUILD_TYPE --output-on-failure)
